#!/bin/bash
#
#SBATCH --mail-type=ALL
#SBATCH --mail-user=jbarham3@uab.edu
#SBATCH --job-name=J15i_Setbp1
#SBATCH --ntasks=1
#SBATCH --mem-per-cpu=64000
#SBATCH --nodes=1
#SBATCH --cpus-per-task=4
#SBATCH --time=48:00:00
#SBATCH --partition=long
#SBATCH --error=%j.%N.err.txt
#SBATCH --output=%j.%N.out.txt

########################################
### PUT YOUR COMMANDS BELOW THIS BOX ###
########################################
cd /data/project/lasseigne_lab/JordanWhitlock/jw_setbp1/introns_processed_data

module load CellRanger/6.1.1

cellranger count --id=J-15 \
                 --transcriptome=/data/project/lasseigne_lab/JordanWhitlock/jw_refs/refdata-gex-mm10-2020-A \
                 --fastqs=/data/project/lasseigne_lab/JordanWhitlock/jw_setbp1 \
                 --sample=J-15 \
		 --include-introns
