#!/bin/bash
#
#general job information
#SBATCH --job-name=hulksmsh
#SBATCH --mail-type=ALL
#SBATCH --mail-user=jwhitlock@uab.edu
#
#Number of tasks needed for this job, the partition, and parameters
#SBATCH --ntasks=1
#SBATCH --mem-per-cpu=255000
#SBATCH --nodes=1
#SBATCH --time=48:00:00
#SBATCH --partition=largemem
#
#outputs from this job
#SBATCH --error=leiden.err
#SBATCH --output=leiden.out

########################################
### PUT YOUR COMMANDS BELOW THIS BOX ###
########################################

module load R/4.1.0-foss-2021a
Rscript Setbp1_Clustering_leiden_04.R