#!/bin/bash
#
#SBATCH --job-name=All_cortex
#SBATCH --mail-type=ALL
#SBATCH --mail-user=jwhitlock@uab.edu #CHANGE THE EMAIL TO YOUR OWN
#
#Number of tasks needed for this job, the partition, and parameters
#SBATCH --ntasks=1
#SBATCH --mem-per-cpu=255000
#SBATCH --nodes=1
#SBATCH --time=150:00:00
#SBATCH --partition=long
#
#SBATCH --output=All_cortex.out
#SBATCH --error=All_cortex.err


########################################
### PUT YOUR COMMANDS BELOW THIS BOX ###
########################################

#Set your environment here
module load R/4.2.0-foss-2021a

#script to call on
Rscript Setbp1_cortex_PANDA.R

#Note final runtime and job info: Slurm Job_id=20060722 Name=All_cortex Ended, Run time 21:16:52