---
title: "07_MouseSetbp1_decoupleR_expression"
author: "Jordan Whitlock"
date: '2023-05-12'
output: html_document
---
```{r}
set.seed(2178)
library(lintr)
library(styler)
library(here)
```


```{r}
load(here("data/kidney_integrated_celltypes_postSoup.Rdata"))
load(here("data/setbp1_cerebralintcelltypes.Rdata"))
```

```{r}
cerebral_decoupleR_expression <- list()

for ( i in levels(cerebral_int_celltypes)){
  data <- subset(cerebral_int_celltypes, subset = (type == "heterozygous" & cell_type == i))
  data <- as.data.frame(data@assays$RNA@data)
  cerebral_decoupleR_expression[[paste0("heterozygous_", i)]] <- data
  
  data <- subset(cerebral_int_celltypes, subset = (type == "control" & cell_type == i))
  data <- as.data.frame(data@assays$RNA@data)
  cerebral_decoupleR_expression[[paste0("control_", i)]] <- data
  
}

save(cerebral_decoupleR_expression, file = here("data/processed/decoupleR_expression_inputs/cerebral_expression.Rdata"))
```

```{r}
kidney_decoupleR_expression <- list()

for ( i in levels(kidney_int_celltypes)){
  data <- subset(kidney_int_celltypes, subset = (type == "heterozygous" & cell_type == i))
  data <- as.data.frame(data@assays$RNA@data)
  kidney_decoupleR_expression[[paste0("heterozygous_", i)]] <- data
  
  data <- subset(kidney_int_celltypes, subset = (type == "control" & cell_type == i))
  data <- as.data.frame(data@assays$RNA@data)
  kidney_decoupleR_expression[[paste0("control_", i)]] <- data
  
}

save(kidney_decoupleR_expression, file = here("data/processed/decoupleR_expression_inputs/kidney_expression.Rdata"))
```


